[package]
name = "listitem"
version = "0.4.0"
authors = ["jgerber <jlgerber@gmail.com>"]
edition = "2018"

[dependencies]
qt_core = "0.4.1"
qt_gui = "0.4.1"
qt_widgets = "0.4.1"
qt_ui_tools = "0.4.1"
log = "0.4.8"
